POST http://localhost:8080/administrator/login
Accept: application/json
Content-Type: application/json

{
  "email": "sil@gmail.com",
  "password": "abc1234"
}

###
POST http://localhost:8080/hospital
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZEFkbWluIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTYyMjc1NjIzMywiZXhwIjoxNjIyODQyNjMzfQ.1EkjHX35P8BVkavnbOGQ8kLWD1P6z7ifctS8uPK8P978PS7p5LtE5fpz2lhnhvdBgUO_lnmMYNkEA5LqeW3FsA

{
  "idDepartment": "BOL1293",
  "name": "Insumos Trinidad",
  "location": "C. Serafin Rivero",
  "phoneNumber":"7894561",
  "lat": -14.82628,
  "lng": -64.89580
}
###
POST http://localhost:8080/pharmacy
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZEFkbWluIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTYyMjc0Mjc4NCwiZXhwIjoxNjIyODI5MTg0fQ.T75pxHsiHRt1j8j7xc9azArduZTqblBkdlfGH2tNOfCnVwIJdZz32lqQDDzY2PaVb_l5RHsjBulVxBs7WQIX_w

{
  "idDepartment": "BOL1293",
  "name": "Obrero",
  "location": "Miraflores",
  "phoneNumber":"852369",
  "lat": 32.85,
  "lng": 68.416
}

###
PUT http://localhost:8080/hospital
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZEFkbWluIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTYyMjc1MTk0NiwiZXhwIjoxNjIyODM4MzQ2fQ.pfP_DmMBhT34zqoHmgUoPPyfbp1qDEVr5mCVn_7EmnOqL_aBW1uG-ARW1Hkh56jHgOWasrJwTmFVKP_sW-8OnQ

{
  "idHospital": 1,
  "idDepartment": "BOL1293",
  "name": "Insumos Trinidad",
  "location": "C. Serafin Rivero",
  "phoneNumber":"7894561",
  "lat": -14.82628,
  "lng": -64.89580
}
###
PUT http://localhost:8080/pharmacy
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZEFkbWluIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTYyMjc1MTk0NiwiZXhwIjoxNjIyODM4MzQ2fQ.pfP_DmMBhT34zqoHmgUoPPyfbp1qDEVr5mCVn_7EmnOqL_aBW1uG-ARW1Hkh56jHgOWasrJwTmFVKP_sW-8OnQ

{
  "idPharmacy": 1,
  "idDepartment": "BOL1293",
  "name": "Insumos Trinidad",
  "location": "C. Serafin Rivero",
  "phoneNumber":"7894561",
  "lat": -14.82628,
  "lng": -64.89580
}

###
DELETE http://localhost:8080/hospital/85
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZEFkbWluIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTYyMjc1MzI1MCwiZXhwIjoxNjIyODM5NjUwfQ.Z1ctBp9HqkCabfNnNKyzBXW7hrIkMJnghsN4ZYe_-USH6MibLueuyeIMI7ftO8UAjbK-GsFnJSNoAz5OlP737A


###
GET http://localhost:8080/hospital
Accept: application/json
Content-Type: application/json


###
GET http://localhost:8080/pharmacy
Accept: application/json
Content-Type: application/json

