POST http://localhost:8080/administrator/login
Accept: application/json
Content-Type: application/json

{
  "email": "sil@gmail.com",
  "password": "abc1234"
}

###
POST http://localhost:8080/hospital
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZEFkbWluIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTYyMjMwNDMxNiwiZXhwIjoxNjIyMzkwNzE2fQ.w31EwQ7xDFtl1OPqtPl4_UP1wGmRTY5O3ziMurmzMEaVBYyB54-584y2S2Q3VIsm0IyoWAztCNt5V0l8UKXNow

{
  "idDepartment": "BOL1293",
  "name": "Obrero",
  "location": "Miraflores",
  "phoneNumber":"852369",
  "lat": 32.85,
  "lng": 68.416
}

###
POST http://localhost:8080/pharmacy
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJpZEFkbWluIjoxLCJhbGciOiJIUzUxMiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImlhdCI6MTYyMjMwNDMxNiwiZXhwIjoxNjIyMzkwNzE2fQ.w31EwQ7xDFtl1OPqtPl4_UP1wGmRTY5O3ziMurmzMEaVBYyB54-584y2S2Q3VIsm0IyoWAztCNt5V0l8UKXNow

{
  "idDepartment": "BOL1293",
  "name": "Cruz Roja",
  "location": "Miraflores",
  "phoneNumber":"7894561",
  "lat": 32.85,
  "lng": 68.416
}

###
GET http://localhost:8080/hospital
Accept: application/json
Content-Type: application/json


###
GET http://localhost:8080/pharmacy
Accept: application/json
Content-Type: application/json

