GET http://localhost:8080/datecountry?date1=2021-01-01&date2=2021-01-07
Accept: application/json

###
GET http://localhost:80/api/item?id=99
Accept: application/json

###
GET http://localhost:8080/world_cases
Accept: application/json

###
GET http://localhost:8080/municipios/BOL1293
Accept: application/json

###
GET http://localhost:8080/world
Accept: application/json

###
GET http://localhost:8080/municipios
Accept: application/json

###
GET http://localhost:8080/department/BOL1293?date1=2021-01-01&date2=2021-01-07
Accept: application/json

###
GET http://localhost:8080/bol_cases
Accept: application/json

###
GET http://localhost:8080/country?id=AFG&date1=2021-01-01&date2=2021-01-07
Accept: application/json

###

GET http://localhost:8080/department?id=BOL1291&date1=2021-01-01&date2=2021-01-07
Accept: application/json

###



GET http://localhost:8080/prediction/gray/country/AFG?cant=5&filter=2
Accept: application/json
###

GET http://localhost:8080/prediction/gray/department/BOL1293?cant=5&filter=0
Accept: application/json
###
GET http://localhost:8080/prediction/gray/municipio/tj0?cant=5&filter=0
Accept: application/json
###
GET http://localhost:8080/prediction/mtx/country/AFG?cant=10&filter=1
Accept: application/json
###
GET http://localhost:8080/prediction/mtx/department/BOL1293?cant=5&filter=2
Accept: application/json
###
GET http://localhost:8080/prediction/mtx/municipio/tj0?cant=5&filter=1
Accept: application/json
###
GET http://localhost:8080/country/average/BOL
Accept: application/json

###
GET http://localhost:8080/department/average/BOL1941
Accept: application/json

###
GET http://localhost:8080/municipios/average?id=tj5
Accept: application/json

###
